config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  devise_for :users
  resources :courses
  resources :mentors
  root 'courses#index'
  resources :carts, only: [:create, :index] do 
    # collection is for plurals has_many relationship - does not require id
    # member is for singular - has id
    collection do
      delete('/remove', to: 'carts#destroy')
    end
  end
  resources :orders, only: [:index, :show] 
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud

    can :read, :all # for guests

    if user.present? # for users
      can :read, :all

      if user.is_student?
        can :read, Course
      elsif user.is_mentor? # for mentor
        can :crud, Course, user_id: user.id
      elsif user.is_admin? # for admin
        can :manage, :all
      end

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :carts_courses
  has_many :courses, through: :carts_courses
end

app/models/carts_course.rb
class CartsCourse < ApplicationRecord
  belongs_to :cart
  belongs_to :course
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses_categories
  has_many :courses, through: :courses_categories
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, :sub_title, presence: true, length: {
    minimum: 5, message: 'and sub title need to be more than 5 letters'
  }
  validates :description, presence: true, length: {
    minimum: 10, message: 'Please enter more than 10 letters'
  }
  validates :price, numericality: {
    message: "%{value} is not valid. Please enter numbers only"
  }
  # validates :image, presence: true

  belongs_to :user
  has_one_attached :image
  has_many :orders
  # has_many :users, through: :orders
  has_many :courses_categories, dependent: :destroy
  has_many :categories, through: :courses_categories
  has_many :testimonials
  # has_many :users, through: :testimonials
  has_many :carts_courses
  has_many :carts, through: :carts_courses

  def display_currency
    '$' + sprintf('%.2f', (self.price))
  end
end

app/models/courses_category.rb
class CoursesCategory < ApplicationRecord
  belongs_to :course
  belongs_to :category
end

app/models/mentor.rb
class Mentor < ApplicationRecord
  belongs_to :user
  validates :description, presence: true
  validates :expertise, presence: true
  validates :business, presence: true
  validates :industry, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  before_create :update_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :mentor, dependent: :destroy
  has_many :courses
  validates_presence_of :first_name, :last_name
  has_many :orders, dependent: :destroy
  has_many :purchased_courses, through: :orders, source: :course
  has_many :testimonials
  # has_many :courses, through: :testimonials
  has_one :cart, dependent: :destroy

  def update_role
    unless self.is_admin
      if self.is_mentor
        self.is_student = false
      else
        self.is_student = true
      end
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # to show all cart items
  def index
    if user_signed_in? && current_user.cart && current_user.is_student?
      @cart_items = cart_items # all items in the cart
      @total_costs = cart_total # total costs of current items in the cart
    else
      redirect_to courses_path
    end
  end

  # all items in the cart
  def cart_items
    current_user.cart.courses.includes(image_attachment: :blob)
  end

  # sums up the price of all items currently in the cart
  def cart_total
    sum = 0
    @cart_items.each do |course|
      sum += (course.price * 1)
    end
    return sum
  end

  # check if user has a cart and if user is a student
  # if conditions fulfilled, use same cart and add course into cart
  def create
    if current_user.is_student? && !current_user.cart
      @cart = current_user.create_cart
    else
      @cart = current_user.cart
    end

    @course = Course.find(params[:course_id])
    @cart.courses << @course # this essentially create a joined table
    flash[:notice] = "Successfully added #{@course.title} to cart"

    redirect_to courses_path
  end

  # remove selected course from user cart 
  def destroy
    @courses = current_user.cart.carts_courses.where(
      course_id: params[:course_id]
    )

    @courses.first.destroy

    redirect_to carts_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # show all courses
  def index
    @courses = Course.with_attached_image.all
  end

  # show selected course
  def show
  end

  # this is where user is sent to course creation form
  def new
    @course = Course.new
  end

  # create and save course into database if inputs are valid
  def create
    @course = current_user.courses.create(course_params)

    if @course.errors.any?
      render :new
    else
      @course.save
      flash[:success] = "You successfully created a new listing!"
      redirect_to @course
    end
  end

  def edit
  end

  # updates course information
  def update
    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  # delete a course from database
  def destroy
    @course.destroy
    redirect_to courses_path
    flash[:notice] = "#{@course.title} has been deleted"
  end

  private
  # sanitises user inputs in course creation form
  def course_params
    params.require(:course).permit(:title, :sub_title, :description, :price, :image)
  end

  # refactor course finding by id code from above into the below method to run before any action
  # this save lines of code and keep the code DRY
  def set_course
    @course = Course.find_by_id(params[:id])

    if @course == nil
      redirect_to courses_path
      flash[:alert] = "Sorry, the course you are looking for doesn't exist"
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # shows all courses purchased by a student
  def index
    orders = Order.all.where(user_id: current_user.id)

    @courses = orders.map do |order|
      Course.find(order.course_id)
    end
    # raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

  # check for image presence and ensure default image is used if necessary
  def image_for(course)
    if course.image.present?
      course.image
    else
      'biztrek_default.jpg'
    end
  end

  # this checks if user has already purchased the course
  # if they have, hide add to cart button
  def purchased_courses(course)
    Order.where(user_id: current_user.id, course_id: course.id).exists?
  end

end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- need to add logo link here -->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? && !current_user.is_student? %>
        <%= link_to 'Add Course', new_course_path, class: 'nav-item nav-link active' %>
      <% end %> 
    </div>
    <div class="navbar-nav">
      <% unless user_signed_in? %>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-outline-success ml-1' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-success ml-1' %>
      <% else %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biztrek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_banner.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner carousel-image-size bleed">
  <!-- insert logic to show only when there are assests set by users / also user can control to display or not-->
    <div class="carousel-item active">
      <%= image_tag 'banner1.jpg', class: "d-block w-100" %>
      <%# <div class="carousel-caption d-none d-md-block">
        <h2 class="text-color">Event: Elon Tusk - How to run business in Mars</h2>
        <p class="text-color">Happening on 22th of September 2020</p>
      </div> %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'banner2.jpg', class: "d-block w-100" %>
      <%# <div class="carousel-caption d-none d-md-block">
        <h2 class="text-color">Learn business in your favoured industry</h2>
        <p class="text-color">Get in touch!</p>
      </div> %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'banner3.jpg', class: "d-block w-100" %>
      <%# <div class="carousel-caption d-none d-md-block">
        <h2 class="text-color">What are you waiting for?</h2>
        <p class="text-color">Sign up with us and connect with our mentors who are industry leaders</p>
      </div> %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_card.html.erb
<div class="card text-center my-3 col-md-4 col-xs-12" style="max-width:30%; min-width:18rem;">
  <%= image_tag image_for(course), alt: "#{course.title} image", class: 'card-img-top img_fluid' %>
  <div class="card-body">
    <h5 class="card-title"><%= course.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= course.sub_title %></h6>
    <p class="card-text"><%= course.price %></p>
    <p class="card-text"><%= course.description %></p>

    <%= link_to 'View', course_path(course), class: 'btn btn-primary' %>
  </div>
</div>

app/views/shared/_course_content.html.erb
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Unit 1
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Unit 2
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Unit 3
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @course, local: true do |form| %>

  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= form.label :sub_title %>
    <%= form.text_field :sub_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  
  <div class="custom-file">
    <%= form.label :image, class: 'custom-file-label' %>
    <%= form.file_field :image, class: 'custom-file-input', id: 'customFile' %>
  </div> 

  <div>
    <%= form.submit class: 'btn btn-success my-2' %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to image_tag("logo.png", size: "100x60", alt: "BizTrek logo"), root_path, class: 'navbar-brand logo-size' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? && !current_user.is_student? %>
        <%= link_to 'Add Course', new_course_path, class: "btn btn-primary add-course" %>
      <% end %> 
      <% unless user_signed_in? %>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-outline-success ml-1' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-success ml-1' %>
      <% else %>
        <% if current_user.is_student? %>
          <%= link_to 'My Purchases', orders_path, class: 'btn btn-outline-success ml-1' %>
          <%= link_to "Cart", carts_path, class: "btn btn-outline-secondary" %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
        <% elsif current_user.is_mentor? %>
          <%= link_to 'My Courses', mentors_path, class: 'btn btn-outline-success ml-1' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
        <% elsif current_user.is_admin? %>
          <%= link_to 'My Purchases', orders_path, class: 'btn btn-outline-success ml-1' %>
          <%= link_to "Cart", carts_path, class: "btn btn-outline-secondary" %>
          <%= link_to 'My Courses', mentors_path, class: 'btn btn-outline-success ml-1' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>