config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  devise_for :users
  resources :courses
  resources :mentors
  root 'courses#index'
  resources :carts, only: [:create, :index] do 
    # collection is for plurals has_many relationship - does not require id
    # member is for singular - has id
    collection do
      delete('/remove', to: 'carts#destroy')
    end
  end
  resources :orders, only: [:index, :show] 
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :carts_courses
  has_many :courses, through: :carts_courses
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # to show all cart items
  def index
    if user_signed_in? && current_user.cart && current_user.is_student?
      @cart_items = cart_items # all items in the cart
      @total_costs = cart_total # total costs of current items in the cart
    else
      redirect_to courses_path
    end
  end

  # all items in the cart
  def cart_items
    current_user.cart.courses.includes(image_attachment: :blob)
  end

  # sums up the price of all items currently in the cart
  def cart_total
    sum = 0
    @cart_items.each do |course|
      sum += (course.price * 1)
    end
    return sum
  end

  # check if user has a cart and if user is a student
  # if conditions fulfilled, use same cart and add course into cart
  def create
    if current_user.is_student? && !current_user.cart
      @cart = current_user.create_cart
    else
      @cart = current_user.cart
    end

    @course = Course.find(params[:course_id])
    @cart.courses << @course # this essentially create a joined table
    flash[:notice] = "Successfully added #{@course.title} to cart"

    redirect_to courses_path
  end

  # remove selected course from user cart 
  def destroy
    @courses = current_user.cart.carts_courses.where(
      course_id: params[:course_id]
    )

    @courses.first.destroy

    redirect_to carts_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<h1>Cart</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Image</th>
        <th scope="col">Course Title</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
      </tr>
    </thead>

    
    <tbody>
    <% n = 1 %>
    <% @cart_items.each do |course| %>
      <tr>
        <th scope="row"><%= "#{n}" %></th>
        <td><%= image_tag course.image , alt: "#{course.title} image", class: 'mt-2', style: 'width:100%' %></td>
        <td><%= course.title %></td>
        <td><%= number_to_currency(course.price) %></td>
        <td>1</td>
        <td><%= link_to 'Remove', remove_carts_path(course_id: course.id), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to remove #{course.title} from cart?"} %></td>
      </tr>
      <% n += 1 %>
    <% end %>
    </tbody>
    <tbody>
    <tr>
      <th>Total: <%= number_to_currency(@total_costs.inspect) %></th>
    </tr>
    </tbody>
  </table>

<%= link_to "Pay Now 💵", "", id: "stripe", class: "btn btn-success btn-lg btn-block" %>

<%= javascript_pack_tag "stripe" %>