config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  devise_for :users
  resources :courses
  resources :mentors
  root 'courses#index'
  resources :carts, only: [:create, :index] do 
    # collection is for plurals has_many relationship - does not require id
    # member is for singular - has id
    collection do
      delete('/remove', to: 'carts#destroy')
    end
  end
  resources :orders, only: [:index, :show] 
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # show all courses
  def index
    @courses = Course.with_attached_image.all
  end

  # show selected course
  def show
  end

  # this is where user is sent to course creation form
  def new
    @course = Course.new
  end

  # create and save course into database if inputs are valid
  def create
    @course = current_user.courses.create(course_params)

    if @course.errors.any?
      render :new
    else
      @course.save
      flash[:success] = "You successfully created a new listing!"
      redirect_to @course
    end
  end

  def edit
  end

  # updates course information
  def update
    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  # delete a course from database
  def destroy
    @course.destroy
    redirect_to courses_path
    flash[:notice] = "#{@course.title} has been deleted"
  end

  private
  # sanitises user inputs in course creation form
  def course_params
    params.require(:course).permit(:title, :sub_title, :description, :price, :image)
  end

  # refactor course finding by id code from above into the below method to run before any action
  # this save lines of code and keep the code DRY
  def set_course
    @course = Course.find_by_id(params[:id])

    if @course == nil
      redirect_to courses_path
      flash[:alert] = "Sorry, the course you are looking for doesn't exist"
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper

  # check for image presence and ensure default image is used if necessary
  def image_for(course)
    if course.image.present?
      course.image
    else
      'biztrek_default.jpg'
    end
  end

  # this checks if user has already purchased the course
  # if they have, hide add to cart button
  def purchased_courses(course)
    Order.where(user_id: current_user.id, course_id: course.id).exists?
  end

end

app/views/courses/added_by_mentor.html.erb
<h1>Welcome back, <em><%= current_user.first_name %></em></h1>

app/views/courses/edit.html.erb
<h1>Edit <%= @course.title %></h1>

<%= render 'shared/form' %>

<%= link_to 'Back', course_path(@course), class: 'btn btn-primary' %>

app/views/courses/index.html.erb
<%= render 'shared/banner' %>
<%# to add category for courses %>
<h3>category</h3>
  <div class="row justify-content-around pt-5">
    <% @courses.each do |course| %>
      <%= render 'shared/card', course: course %>
      <% end %>
  </div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render '/shared/form' %>

<%= link_to 'Back', courses_path, class: 'btn btn-primary' %>

app/views/courses/show.html.erb
<div class="row content mt-3">
  <div class="col-md-4">
    <%= image_tag image_for(@course) , alt: "#{@course.title} image", class: 'mt-2', style: 'width:100%;' %>
  </div> 
  <div class="col-md-8">
    <h1><%= @course.title %></h1>
    <div>
      <strong>Sub-title:  </strong>
      <span><%= @course.sub_title %></span>
    </div>
    <div>
      <strong>Price:  </strong>
      <span><%= number_to_currency(@course.price) %></span>
    </div>
    <p><%= @course.description %></p>

    <div class='gotta set margin'>
    <!-- only show edit and delete buttons when user has the power to edit the object -->
    <% if can? :edit, @course %> 
    <%= link_to 'Edit', edit_course_path(@course), class: 'btn btn-info'%>
    <%= link_to 'Delete', course_path(@course), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete #{@course.title}?"} %>
    <% end %>
    
    <% if user_signed_in? && current_user.is_student? && !purchased_courses(@course)  %>
    <%= link_to "Add to cart", carts_path(course_id: @course.id), method: :post  %>
    <% end %>

    <%= link_to 'Back', courses_path, class: 'btn btn-primary' %> 
    </div>
  
    <%= render '/shared/course_content' %>
  </div>
</div>